---

- hosts: all
  tasks:
    - name: kill all ossec processors
      command: pkill -f "ossec"
      ignore_errors: yes

    - name: remove installation directory, user, group, Configurations
      command: >
        sudo rm -f /etc/init.d/ossec /etc/rc0.d/K20ossec /etc/rc1.d/K20ossec /etc/rc2.d/S20ossec /etc/rc3.d/S20ossec /etc/rc4.d/S20ossec /etc/rc5.d/S20ossec /etc/rc6.d/K20ossec;
        sudo rm -rf /var/ossec;
        sudo /usr/sbin/deluser ossec;
        sudo /usr/sbin/deluser ossecm;
        sudo /usr/sbin/deluser ossecr;
        sudo /usr/sbin/deluser ossecd;
        sudo /usr/sbin/delgroup ossec;
        sudo /usr/sbin/delgroup ossecd