---

- name: modify preloaded-vars for agent-side
  template: >
    src=preloaded-vars-hybrid.j2
    dest="/usr/local/src/ossec-hids-{{ ossec_ver }}/etc/preloaded-vars.conf"
    force=yes
    owner=root
    group=root
    mode=0755

- name: install ossec agent-side
  shell: ./install.sh chdir="/usr/local/src/ossec-hids-{{ ossec_ver }}/"